### ISSUE TITLE
소셜로그인(카카오로그인 react/node.js 협업)

### ISSUE THREAD

**Issue by sooyeon29** [eunrain/spots-fe#22]
[카카오소셜로그인]
아래 3가지 방법을 찾아보고 진행중
1. 백엔드 passport 사용 프런트로 리다이렉트url만 연결로시도
 -> 경로설정issue발생
2. 프런트 인가코드 받기 ok -> 백으로 인가코드 ?code=${code} api경로로 전달
-> 백에서 인가코드를 카카오로 전달 및 토큰 받는 부분에서 issue발생
(새로운 정보(코드)를 찾아서 전달해놓은상태 - 아직 적용전)
3. 프런트에서 인가코드 받기 ok -> 프런트에서 토큰 받기 => KOE101 에러!)!
KOE101: 잘못된 앱 키 타입을 사용하거나 앱 키에 오타가 있을 경우 => 확인완료...안되네요..

**Comment by sooyeon29** [comment]
map을 이용하여 비교할 대상을 미리 변수에 담음
disabled={timeSlots.includes(myTime[0])}
이를 includes() 함수를 이용하여 ture값으로 반환 받음

**Comment by sooyeon29** [comment]
params에서 get한 인가코드를
axios.get을 이용하여 백으로 전달하고 토큰을 받음
=> auth/kakao/code?code=${payload}
인가코드를 전달할때 쿼리문으로 전달

백엔드에서 카카오 측으로 토큰과 사용자 정보를 받을때도 axios를 사용
->화면공유를 통해 함께 소통하고 실행해보며 문제 해결

**Comment by MiraeKim1031** [comment]
페이지가 렌더링 된 후 토큰이 백엔드로 넘어가 새로고침을 해야만 로그인 상의 기능을 할 수 있는 상황. Axios interceptor를 이용해 매 request 전 토큰이 있는지 검수하고 백으로 토큰을 전달.
