### ISSUE TITLE
검색기능

### ISSUE THREAD

**Issue by sooyeon29** [eunrain/spots-fe#79]
1. db에서 get으로 가져온 내용을 filter처리를 통하여 검색기능구현
-> 새로고침시 검색어가 null값이 되어 렌더링 실패
2. 검색어를 쿼리문으로 백엔드로 전달하여 검색결과를 받는 방법으로 검색기능 구현
-> 위와 같이 검색어가 없는 경우가 생김
-> 백엔드에서는 공공과 사설의 두개의 다른 정보를 함께 검색하여 전달레서 오류발생

**Comment by MiraeKim1031** [comment]
검색어가 없는 경우(Params 없음), 있는 경우(Params 있음) 두 조건일 때를 분기하여 두 개의 useEffect를 사용. 검색 결과 또한 검색어 없이 전체 목록을 보여주는 경우에는 전체 리스트 배열에 map 메서드를 사용, 검색어가 있는 경우에는 서버에서 받아온 검색 결과를 배열에 넣어 map 메서드를 사용함.
